import type { Tool } from "./types.js";

const PDF = "application/pdf";
// pdf-lib can embed JPG and PNG natively; webp needs a sharp pre-pass (Phase 2).
const IMG = ["image/jpeg", "image/png"];

/**
 * The single source of truth for every tool in PDFForge.
 * The homepage grid, search, category tabs, mega-menu, and the dynamic
 * `/[slug]` routes are all generated from this array.
 *
 * Adding a tool = add an entry here + a processor in `@pdfforge/pdf-core`
 * (or a worker) + an options component in the web app.
 */
export const TOOLS: Tool[] = [
  // ── A. Organize ──────────────────────────────────────────────
  {
    slug: "merge-pdf",
    title: "Merge PDF",
    category: "organize",
    description: "Combine multiple PDFs into one. Drag to reorder.",
    icon: "Combine",
    accepts: [PDF],
    multiple: true,
    processing: "sync",
    maxFiles: 30,
    phase: 1,
    implemented: true,
  },
  {
    slug: "split-pdf",
    title: "Split PDF",
    category: "organize",
    description: "Split by ranges, into single pages, or every N pages.",
    icon: "Scissors",
    accepts: [PDF],
    multiple: false,
    processing: "sync",
    phase: 1,
    implemented: true,
  },
  {
    slug: "remove-pages",
    title: "Remove Pages",
    category: "organize",
    description: "Delete selected pages from your PDF.",
    icon: "FileMinus",
    accepts: [PDF],
    multiple: false,
    processing: "sync",
    phase: 1,
    implemented: true,
  },
  {
    slug: "extract-pages",
    title: "Extract Pages",
    category: "organize",
    description: "Keep only the pages you choose as a new PDF.",
    icon: "FileOutput",
    accepts: [PDF],
    multiple: false,
    processing: "sync",
    phase: 1,
    implemented: true,
  },
  {
    slug: "organize-pdf",
    title: "Organize PDF",
    category: "organize",
    description: "Reorder, rotate, and delete pages in a visual manager.",
    icon: "LayoutGrid",
    accepts: [PDF],
    multiple: false,
    processing: "sync",
    phase: 1,
    implemented: true,
  },
  {
    slug: "scan-to-pdf",
    title: "Scan to PDF",
    category: "organize",
    description: "Capture from your camera or images and build a PDF.",
    icon: "ScanLine",
    accepts: IMG,
    multiple: true,
    processing: "sync",
    phase: 1,
    implemented: true,
  },

  // ── B. Optimize ──────────────────────────────────────────────
  {
    slug: "compress-pdf",
    title: "Compress PDF",
    category: "optimize",
    description: "Reduce file size with quality presets.",
    icon: "Minimize2",
    accepts: [PDF],
    multiple: false,
    processing: "sync",
    phase: 2,
    implemented: true,
  },
  {
    slug: "repair-pdf",
    title: "Repair PDF",
    category: "optimize",
    description: "Recover data from a corrupt or damaged PDF.",
    icon: "Wrench",
    accepts: [PDF],
    multiple: false,
    processing: "async",
    phase: 2,
    implemented: false,
  },
  {
    slug: "ocr-pdf",
    title: "OCR PDF",
    category: "optimize",
    description: "Make scanned PDFs selectable and searchable.",
    icon: "ScanText",
    accepts: [PDF],
    multiple: false,
    processing: "async",
    phase: 2,
    implemented: false,
  },

  // ── C. Convert to PDF ────────────────────────────────────────
  {
    slug: "jpg-to-pdf",
    title: "JPG to PDF",
    category: "convert",
    description: "Turn images into a PDF with layout options.",
    icon: "Image",
    accepts: IMG,
    multiple: true,
    processing: "sync",
    phase: 1,
    implemented: true,
  },
  {
    slug: "word-to-pdf",
    title: "Word to PDF",
    category: "convert",
    description: "Convert DOC and DOCX documents to PDF.",
    icon: "FileText",
    accepts: [
      "application/msword",
      "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    ],
    multiple: false,
    processing: "async",
    phase: 2,
    implemented: false,
  },
  {
    slug: "powerpoint-to-pdf",
    title: "PowerPoint to PDF",
    category: "convert",
    description: "Convert PPT and PPTX slides to PDF.",
    icon: "Presentation",
    accepts: [
      "application/vnd.ms-powerpoint",
      "application/vnd.openxmlformats-officedocument.presentationml.presentation",
    ],
    multiple: false,
    processing: "async",
    phase: 2,
    implemented: false,
  },
  {
    slug: "excel-to-pdf",
    title: "Excel to PDF",
    category: "convert",
    description: "Convert XLS and XLSX spreadsheets to PDF.",
    icon: "Sheet",
    accepts: [
      "application/vnd.ms-excel",
      "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    ],
    multiple: false,
    processing: "async",
    phase: 2,
    implemented: false,
  },
  {
    slug: "html-to-pdf",
    title: "HTML to PDF",
    category: "convert",
    description: "Convert a web page URL or HTML file to PDF.",
    icon: "Code",
    accepts: ["text/html"],
    multiple: false,
    processing: "async",
    phase: 2,
    implemented: false,
  },

  // ── D. Convert from PDF ──────────────────────────────────────
  {
    slug: "pdf-to-jpg",
    title: "PDF to JPG",
    category: "convert",
    description: "Render each page to an image, or extract images.",
    icon: "Images",
    accepts: [PDF],
    multiple: false,
    processing: "sync",
    phase: 1,
    implemented: true,
  },
  {
    slug: "pdf-to-word",
    title: "PDF to Word",
    category: "convert",
    description: "Extract a PDF's text into an editable DOCX document.",
    icon: "FileText",
    accepts: [PDF],
    multiple: false,
    processing: "sync",
    phase: 2,
    implemented: true,
  },
  {
    slug: "pdf-to-powerpoint",
    title: "PDF to PowerPoint",
    category: "convert",
    description: "Convert a PDF into editable PPTX slides.",
    icon: "Presentation",
    accepts: [PDF],
    multiple: false,
    processing: "async",
    phase: 2,
    implemented: false,
  },
  {
    slug: "pdf-to-excel",
    title: "PDF to Excel",
    category: "convert",
    description: "Extract tables from a PDF into XLSX.",
    icon: "Sheet",
    accepts: [PDF],
    multiple: false,
    processing: "async",
    phase: 2,
    implemented: false,
  },
  {
    slug: "pdf-to-pdfa",
    title: "PDF to PDF/A",
    category: "convert",
    description: "Convert to the ISO archival PDF/A format.",
    icon: "Archive",
    accepts: [PDF],
    multiple: false,
    processing: "async",
    phase: 2,
    implemented: false,
  },

  // ── E. Edit ──────────────────────────────────────────────────
  {
    slug: "rotate-pdf",
    title: "Rotate PDF",
    category: "edit",
    description: "Rotate all or selected pages, across many files.",
    icon: "RotateCw",
    accepts: [PDF],
    multiple: true,
    processing: "sync",
    maxFiles: 30,
    phase: 1,
    implemented: true,
  },
  {
    slug: "page-numbers",
    title: "Add Page Numbers",
    category: "edit",
    description: "Insert page numbers with full positioning control.",
    icon: "Hash",
    accepts: [PDF],
    multiple: false,
    processing: "sync",
    phase: 1,
    implemented: true,
  },
  {
    slug: "watermark-pdf",
    title: "Add Watermark",
    category: "edit",
    description: "Stamp text or an image over your PDF.",
    icon: "Stamp",
    accepts: [PDF],
    multiple: false,
    processing: "sync",
    phase: 1,
    implemented: true,
  },
  {
    slug: "crop-pdf",
    title: "Crop PDF",
    category: "edit",
    description: "Set the crop box for one page or all.",
    icon: "Crop",
    accepts: [PDF],
    multiple: false,
    processing: "sync",
    phase: 1,
    implemented: true,
  },
  {
    slug: "edit-pdf",
    title: "Edit PDF",
    category: "edit",
    description: "Add text, images, and shapes, then flatten.",
    icon: "PenTool",
    accepts: [PDF],
    multiple: false,
    processing: "sync",
    phase: 3,
    implemented: true,
  },
  {
    slug: "pdf-forms",
    title: "PDF Forms",
    category: "edit",
    description: "Detect, create, fill, and flatten form fields.",
    icon: "FormInput",
    accepts: [PDF],
    multiple: false,
    processing: "sync",
    phase: 3,
    implemented: false,
  },

  // ── F. Security ──────────────────────────────────────────────
  {
    slug: "unlock-pdf",
    title: "Unlock PDF",
    category: "security",
    description: "Remove a known password or restrictions.",
    icon: "LockOpen",
    accepts: [PDF],
    multiple: false,
    processing: "async",
    phase: 2,
    implemented: false,
  },
  {
    slug: "protect-pdf",
    title: "Protect PDF",
    category: "security",
    description: "Add a password and permission flags (AES-256).",
    icon: "Lock",
    accepts: [PDF],
    multiple: false,
    processing: "async",
    phase: 2,
    implemented: false,
  },
  {
    slug: "sign-pdf",
    title: "Sign PDF",
    category: "security",
    description: "Draw, type, or upload a signature and place it.",
    icon: "Signature",
    accepts: [PDF],
    multiple: false,
    processing: "sync",
    phase: 3,
    implemented: true,
  },
  {
    slug: "redact-pdf",
    title: "Redact PDF",
    category: "security",
    description: "Permanently black out text and regions.",
    icon: "SquareSlash",
    accepts: [PDF],
    multiple: false,
    processing: "async",
    phase: 3,
    implemented: false,
  },
  {
    slug: "compare-pdf",
    title: "Compare PDF",
    category: "security",
    description: "Diff two PDFs side by side.",
    icon: "GitCompare",
    accepts: [PDF],
    multiple: true,
    maxFiles: 2,
    processing: "sync",
    phase: 3,
    implemented: false,
  },

  // ── G. AI ────────────────────────────────────────────────────
  {
    slug: "ai-summarizer",
    title: "AI Summarizer",
    category: "ai",
    description: "Summarize a PDF into key points with AI.",
    icon: "Sparkles",
    accepts: [PDF],
    multiple: false,
    processing: "async",
    phase: 4,
    implemented: false,
  },
  {
    slug: "translate-pdf",
    title: "Translate PDF",
    category: "ai",
    description: "Translate a PDF while preserving layout.",
    icon: "Languages",
    accepts: [PDF],
    multiple: false,
    processing: "async",
    phase: 4,
    implemented: false,
  },
];

export const TOOLS_BY_SLUG: Record<string, Tool> = Object.fromEntries(
  TOOLS.map((t) => [t.slug, t]),
);

export function getTool(slug: string): Tool | undefined {
  return TOOLS_BY_SLUG[slug];
}

export function toolsInCategory(category: string): Tool[] {
  return TOOLS.filter((t) => t.category === category);
}
